// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.28;

import {Script, console} from "forge-std/Script.sol";
import {ERC1967Proxy} from "@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol";
import {Asset} from "../src/Asset.sol";
import {MockBLS} from "../test/MockBLS.sol";
import {ERC20} from "@openzeppelin/contracts/token/ERC20/ERC20.sol";

/// @dev Minimal mock ERC20 for local testing (no real USDC needed).
contract MockUSDC is ERC20 {
    constructor() ERC20("Mock USDC", "USDC") {
        _mint(msg.sender, 1_000_000_000 * 1e18);
    }
    function decimals() public pure override returns (uint8) { return 18; }
}

/// @notice Deploy Asset + MockBLS + MockUSDC on a local Anvil chain for BLS end-to-end testing.
///
/// Usage:
///   # Start anvil first:
///   ./scripts/anvil-start.sh   (chainId=31337, port=8545)
///
///   # Deploy with Anvil account 0 (default key):
///   PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 \
///   forge script script/DeployLocal.s.sol \
///     --rpc-url http://127.0.0.1:8545 \
///     --broadcast -vvv
///
/// Outputs printed to console:
///   MockUSDC   deployed at: <addr>
///   MockBLS    deployed at: <addr>
///   Asset impl deployed at: <addr>
///   Asset proxy deployed at: <addr>   ← fill this into relayer ChainInfo.PoolContractAddress
///
/// Validator EIP-2537 G1 pubkeys used (from TestPrintBatchUpdateVector, sk=0x0101..01/0202..02/0303..03):
///   pk[0] = 128-byte EIP-2537 G1 point for sk=0x0101...01
///   pk[1] = 128-byte EIP-2537 G1 point for sk=0x0202...02
///   pk[2] = 128-byte EIP-2537 G1 point for sk=0x0303...03
contract DeployLocalScript is Script {
    // Anvil default account 0
    address constant ANVIL_ACCOUNT_0 = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266;

    // EIP-2537 G1 pubkeys generated by TestPrintBatchUpdateVector (sk = 0x01*32 / 0x02*32 / 0x03*32)
    bytes constant PK0 =
        hex"000000000000000000000000000000000a1a1c26055a329817a5759d877a2795f9499b97d6056edde0eea39512f24e8bc874b4471f0501127abb1ea0d9f68ac10000000000000000000000000000000011392125a1c3750363c2c97d9650fb78696e6428db8ff9efaf0471cbfd20324916ab545746db83756d335e92f9e8c8b8";
    bytes constant PK1 =
        hex"000000000000000000000000000000000004066a1a5cb9cdf244e45f0a59cf579a78d90ac0bc24663565264601c1c9251c0aa3dfb9835b520e0ba0f211a6696c000000000000000000000000000000000250fee58f12e98c72bd7de41a2c57df2c35452a4abfb0cc2691eb363f7bb9897c38f8f94ab4f8d63673b61128f11b9e";
    bytes constant PK2 =
        hex"000000000000000000000000000000000355519968b7db86b1ceb2261e179f6cde1a6010b8588e4a1a59eae804c9eed5f3e3d433a69dabb1eb7403c9c2721116000000000000000000000000000000000e3e5890e55ee5cd46fbe01d22cfde2f1570f1e6a06c5719fab0bf77ac63f787ff34cecff52085d6369db4eeaed764a3";

    function run() external {
        uint256 deployerPrivKey = vm.envUint("PRIVATE_KEY");
        address deployer = vm.addr(deployerPrivKey);
        console.log("Deployer:", deployer);

        vm.startBroadcast(deployerPrivKey);

        // 1. Deploy mock USDC
        MockUSDC usdc = new MockUSDC();
        console.log("MockUSDC deployed at:", address(usdc));

        // 2. Deploy MockBLS (always returns true, no EIP-2537 precompile needed)
        MockBLS mockBls = new MockBLS();
        console.log("MockBLS deployed at:", address(mockBls));

        // 3. Deploy Asset implementation + proxy
        Asset impl = new Asset();
        console.log("Asset impl deployed at:", address(impl));

        bytes memory initData = abi.encodeWithSelector(
            Asset.initialize.selector,
            address(usdc),
            uint64(1) // defaultCollateralCoinId
        );
        ERC1967Proxy proxy = new ERC1967Proxy(address(impl), initData);
        Asset asset = Asset(payable(address(proxy)));
        console.log("Asset proxy deployed at:", address(proxy));

        // 4. Configure Asset
        // settlementOperator = deployer (same address relayer uses to send txns)
        asset.setSettlementAddress(deployer);
        asset.setWithdrawOperator(deployer);

        // 5. Register MockBLS verifier
        asset.setBls(address(mockBls));

        // 6. Register BLS settlement validators (threshold=2 of 3)
        bytes[] memory pks = new bytes[](3);
        pks[0] = PK0;
        pks[1] = PK1;
        pks[2] = PK2;
        asset.setSettlementValidators(pks, 2);
        console.log("Settlement validators set (threshold=2/3)");

        console.log("");
        console.log("=== Fill these into relayer config/local.yaml ===");
        console.log("ChainInfo.PoolContractAddress:", address(proxy));
        console.log("DeployAddress / DeployerPrivateKey: Anvil account 0");
        console.log("  address:", deployer);
        console.log("  privkey: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80");

        vm.stopBroadcast();
    }
}
